### ISSUE TITLE
Default Selections

### ISSUE THREAD

**Issue by Dtatoo** [dlkb/Keep-It-Tidy#10]
Before the update all tabs and windows were selected by default (when you click the extension icon). Now I have to select them manually or click on "invert selection" before any action can be performed.

One of my most frequent use of the extension was to re-order the tabs and now it takes one extra operation to do this. Would it be possible to revert this behavior back to what is used to be?

**Comment by dlkb** [comment]
I actually thought about this but I didn't want new users to close all their tabs or move all their tabs to one single window by accident, so I removed the selection/subselection mechanic for all actions, including the "sort" action. Having to click the "invert selection" button seemed to be a good compromise.

But I agree that it's often useful to sort all tabs from one window at once, so I will make an exception for the "sort" action.

**Comment by Dtatoo** [comment]
Most of my use of the plugin are: 
- sort tabs
- search -> (operation)
And those two worked with all tabs selected by default without any issues.

I have accidentally closed all selected tabs once when I first used plugin and never made the same mistakes again.
I believe there is value in keeping operations consistent instead of having exception for 'sort' in this case.

**Comment by dlkb** [comment]
I can see why a user may want to remove all tabs from one or more windows, same thing for sort but not so much for "extract" and "pin". I need to redesign the toolbar and I also value consistency, so I will try to improve the UI.
